stages:
  - build_stage
  - deploy_stage   

build:
  stage: build_stage
  script:
  - apt update -y
  - apt npm install -y
  - npm install  

deploy:
  stage: deploy_stage   
  script:
     - apt update -y
     - apt install nodejs -y
     - node app.js
