stages:
  - build_stage
  - deploy_stage

build:
  stage: build_stage
  script:
    - apt update
    - apt install npm -y
    - npm install
  artifacts:
    paths:
      - node_modules
      - package-lock.json 
deploy:
  stage: deploy_stage
  script:
    - apt update - 
    - apt install nodejs 
    - node app.js
    
       