stages:
  - build_stage
  - deploy_stage   

build:
  stages: - build_stage
  script:
  - apt update -y
  - apt install nmp  -y
  - npm  install  

  deploy:
    stages:
    script:- deploy_stage   
    - apt update -y
    - apt install  node.js -y
    - node app.js